# ./Example-Plugin/src/main/resources/config.yml
# Example-Plugin Configuration
# This configuration demonstrates the usage of Core-Utils configuration management

# Plugin features
features:
  # Enable or disable database integration (requires SQL-Bridge)
  database_integration: true
  
  # Enable or disable stat tracking
  stat_tracking: true
  
  # Enable or disable achievements
  achievements: true
  
  # Enable or disable admin tools
  admin_tools: true

# Statistics tracking settings
statistics:
  # Auto-save interval in seconds (set to 0 to disable auto-save)
  save_interval: 300
  
  # Whether to track blocks broken
  track_blocks_broken: true
  
  # Whether to track blocks placed
  track_blocks_placed: true
  
  # Whether to track player kills
  track_player_kills: true
  
  # Whether to track mob kills
  track_mob_kills: true
  
  # Whether to track playtime
  track_playtime: true
  
  # Whether to track distance traveled
  track_distance: true

# Achievement settings
achievements:
  # Whether to announce achievements to all players
  announce_global: true
  
  # Whether to play sound on achievement
  play_sound: true
  
  # Whether to show achievements in player's chat
  show_in_chat: true
  
  # Whether to give rewards for achievements
  enable_rewards: true

# Debug settings
debug:
  # Enable or disable debug mode
  enabled: false
  
  # Log level (0: OFF, 1: SEVERE, 2: WARNING, 3: INFO, 4: FINE, 5: ALL)
  log_level: 3
  
  # Whether to log database operations
  log_database: false
  
  # Whether to log service operations
  log_services: false