# ./Example-Plugin/src/main/resources/plugin.yml
name: PlayerStats
version: '${version}'
main: com.minecraft.example.PlayerStatsPlugin
api-version: '1.16'
depend: [CoreUtils, Sql-Bridge]
description: Example plugin demonstrating CoreUtils and Sql-Bridge functionality
author: Craftingkilla1
website: https://github.com/Craftingkilla1/minecraft-plugins

commands:
  stats:
    description: View player statistics
    usage: /stats [player]
    aliases: [playerstats, pstats]
  
  admin:
    description: Administrative commands for PlayerStats
    usage: /admin <reset|modify|maintenance> [options]
    permission: playerstats.admin
  
  leaderboard:
    description: View server leaderboards
    usage: /leaderboard [category]
    aliases: [top, lb]

permissions:
  playerstats.admin:
    description: Allows access to administrative commands
    default: op
  
  playerstats.view.others:
    description: Allows viewing other players' statistics
    default: op
  
  playerstats.reset:
    description: Allows resetting player statistics
    default: op
    
  playerstats.modify:
    description: Allows modifying player statistics
    default: op