# ./Example-Plugin/src/main/resources/plugin.yml
name: Example-Plugin
version: '${version}'
main: com.minecraft.example.ExamplePlugin
api-version: '1.16'
authors: [Minecraft-Plugins-Team]
description: Example plugin demonstrating Core-Utils and SQL-Bridge functionality
depend: [Core-Utils]
softdepend: [Sql-Bridge]
commands:
  example:
    description: Main command for Example-Plugin
    usage: /example <subcommand> [args]
    aliases: [exp, exampleplugin]
    permission: exampleplugin.use
  stats:
    description: View and manage player statistics
    usage: /stats <subcommand> [args]
    aliases: [playerstats, pstats]
    permission: exampleplugin.stats
  achievements:
    description: View and manage player achievements
    usage: /achievements <subcommand> [args]
    aliases: [achieve, ach]
    permission: exampleplugin.achievements
permissions:
  exampleplugin.use:
    description: Allows use of basic Example-Plugin commands
    default: true
  exampleplugin.stats:
    description: Allows use of stats commands
    default: true
  exampleplugin.stats.others:
    description: Allows viewing stats of other players
    default: op
  exampleplugin.stats.reset:
    description: Allows resetting player stats
    default: op
  exampleplugin.achievements:
    description: Allows use of achievement commands
    default: true
  exampleplugin.achievements.others:
    description: Allows viewing achievements of other players
    default: op
  exampleplugin.achievements.award:
    description: Allows manually awarding achievements to players
    default: op
  exampleplugin.admin:
    description: Provides access to all admin commands
    default: op
    children:
      exampleplugin.stats.reset: true
      exampleplugin.stats.others: true
      exampleplugin.achievements.others: true
      exampleplugin.achievements.award: true