# ./Sql-Bridge/src/main/resources/config.yml
# SQL-Bridge Configuration

# Debug mode - enables additional logging
debug: false

# Database configuration
database:
  # Database type: MYSQL, POSTGRESQL, SQLITE, H2
  type: sqlite
  
  # MySQL configuration
  mysql:
    host: localhost
    port: 3306
    database: minecraft
    username: root
    password: password
    # Whether to create the database if it doesn't exist
    auto-create-database: true
    
    # Connection pool settings
    pool:
      # Maximum number of connections in the pool
      maximum-pool-size: 10
      # Minimum idle connections
      minimum-idle: 5
      # Maximum lifetime of a connection in milliseconds
      maximum-lifetime: 1800000
      # Connection timeout in milliseconds
      connection-timeout: 5000
      # Allow the pool to self-heal connection failures
      auto-reconnect: true

  # SQLite configuration
  sqlite:
    # Database file (relative to plugin folder)
    file: database.db
    # Whether to use WAL mode for better performance
    wal-mode: true

# BungeeSupport configuration
bungee:
  # Whether to enable BungeeSupport for multi-server setups
  enabled: false
  # Use shared database across BungeeCord network
  shared-database: true

# Security configuration
security:
  # Enable SQL injection detection
  sql-injection-detection: true
  # Log dangerous operations
  log-dangerous-operations: true
  # Maximum query length
  max-query-length: 10000

# Performance monitoring
monitoring:
  # Enable monitoring
  enabled: true
  # Log slow queries that take longer than this many milliseconds
  slow-query-threshold: 1000
  # Collect metrics data
  collect-metrics: true
  # Metrics collection interval in seconds
  metrics-interval: 300

# Migration system
migrations:
  # Automatic migration on startup
  auto-migrate: true
  # Rollback failed migrations
  rollback-failed-migrations: true

# Batch settings
batch:
  # Default batch size for batch operations
  default-size: 100
  # Maximum batch size allowed
  max-size: 1000

# Database thread pool size for async operations
database-thread-pool-size: 4