# ./Sql-Bridge/src/main/resources/config.yml
# SQL-Bridge Configuration

# Debug mode - enables additional logging
debug: false

# Database configuration
database:
  # MySQL configuration
  mysql:
    host: localhost
    port: 3306
    database: minecraft
    username: root
    password: password
    # Whether to create the database if it doesn't exist
    auto-create-database: true
    
    # Connection pool settings (HikariCP)
    pool:
      # Maximum size of the connection pool
      maximum-pool-size: 10
      # Minimum number of idle connections
      minimum-idle: 5
      # Maximum lifetime of a connection in milliseconds
      maximum-lifetime: 1800000
      # Connection timeout in milliseconds
      connection-timeout: 30000
      # How often to check idle connections for validity
      idle-timeout: 600000
      # Keep alive time (in ms)
      keepalive-time: 30000
      # Whether to log connection leaks
      leak-detection-threshold: 30000
  
# BungeeSupport configuration
bungee:
  # Whether to enable BungeeSupport for multi-server setups
  enabled: false
  # Use shared database across BungeeCord network
  shared-database: true

# Security configuration
security:
  # Enable SQL injection detection
  sql-injection-detection: true
  # Log dangerous operations
  log-dangerous-operations: true
  # Maximum query length
  max-query-length: 10000

# Performance monitoring
monitoring:
  # Enable monitoring
  enabled: true
  # Log slow queries that take longer than this many milliseconds
  slow-query-threshold: 1000
  # Collect metrics data
  collect-metrics: true
  # Metrics collection interval in seconds
  metrics-interval: 300

# Migration system
migrations:
  # Automatic migration on startup
  auto-migrate: true
  # Rollback failed migrations
  rollback-failed-migrations: true

# Query batch settings
batch:
  # Default batch size for batch operations
  default-size: 100
  # Maximum batch size allowed
  max-size: 1000

# Database thread pool size for async operations
database-thread-pool-size: 4