# ./Sql-Bridge/src/main/resources/plugin.yml
name: SqlBridge
version: '1.0.4'
main: com.minecraft.sqlbridge.SqlBridgePlugin
api-version: '1.16'
depend: [CoreUtils]
softdepend: []
authors: [MinecraftDevelopmentTeam]
description: A high-performance database middleware plugin that provides a standardized API for SQL database operations.
commands:
  sqlbridge:
    description: Admin commands for the SQL Bridge plugin
    usage: /<command> [info|status|reload|test]
    permission: sqlbridge.admin
permissions:
  sqlbridge.admin:
    description: Allows access to all SQL Bridge admin commands
    default: op
  sqlbridge.info:
    description: Allows access to the SQL Bridge info command
    default: op
  sqlbridge.status:
    description: Allows access to the SQL Bridge status command
    default: op
  sqlbridge.reload:
    description: Allows access to the SQL Bridge reload command
    default: op
  sqlbridge.test:
    description: Allows access to the SQL Bridge test command
    default: op