name: Build and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Core-Utils/build/libs/CoreUtils-*.jar
          Sql-Bridge/build/libs/SqlBridge-*.jar
          Example-Plugin/build/libs/ExamplePlugin-*.jar
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true